# -*- coding: utf-8 -*-
"""amazon.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/10x43aah_Z1AsbN5qGIsqMwG_zdfdPQlq
"""

# Instalar pacotes
!pip install basedosdados -q
!pip install shapely  -q
!pip install geopandas -q

#Importar Pacotes
import basedosdados as bd
import shapely
import geopandas as gpd
import matplotlib.pyplot as plt
import shapely

#Query de Municipio

query ='''
WITH tabela_cnes as (
  SELECT 
    id_municipio,
    sigla_uf,
    sum(quantidade_consultorio_pediatrico) as consultorio_pediatrico,
    FROM `basedosdados.br_ms_cnes.estabelecimento` a 
    WHERE a.ano = 2021 AND 
    a.sigla_uf IN ('AM','AC', 'MT', 'AP', 'PA', 'RO', 'RR', 'TO', 'MA')
    group by id_municipio, sigla_uf
  ),

tabela_populacao as (
SELECT c.id_municipio,
SUM(CASE WHEN c.grupo_idade = '0-4 anos' THEN c.populacao ELSE 0 END) AS populacao_0_4_anos,
SUM(CASE WHEN c.grupo_idade = '5-9 anos' THEN c.populacao ELSE 0 END) AS populacao_5_9_anos,
SUM(CASE WHEN c.grupo_idade = '10-14 anos' THEN c.populacao ELSE 0 END) AS populacao_10_14_anos,
FROM basedosdados-dev.br_ms_populacao.municipio c
WHERE ano = 2021
GROUP BY 1
) 
 
SELECT tabela_cnes.id_municipio,
  tabela_cnes.sigla_uf,  
  tabela_cnes.consultorio_pediatrico,
  tabela_populacao.populacao_0_4_anos,
  tabela_populacao.populacao_5_9_anos,
  tabela_populacao.populacao_10_14_anos,
  populacao_0_4_anos + populacao_5_9_anos + populacao_10_14_anos as pop_criancas_total,
  geometria
  FROM tabela_cnes INNER JOIN tabela_populacao 
  ON tabela_cnes.id_municipio = tabela_populacao.id_municipio
  INNER JOIN `basedosdados.br_geobr_mapas.municipio` d
  ON tabela_cnes.id_municipio = d.id_municipio
'''

df = bd.read_sql(query, billing_project_id='teste-projeto-bd')

#Query de UF
query = '''
WITH tabela_cnes as (
  SELECT
    id_municipio,
    sigla_uf,
    sum(quantidade_consultorio_pediatrico) as consultorio_pediatrico
  FROM `basedosdados.br_ms_cnes.estabelecimento` a 
  WHERE a.ano = 2021 AND
  a.sigla_uf IN ('AM','AC', 'MT', 'AP', 'PA', 'RO', 'RR', 'TO', 'MA')
  GROUP BY sigla_uf, id_municipio
),

tabela_populacao as (
  SELECT c.id_municipio,
    SUM(CASE WHEN c.grupo_idade = '0-4 anos' THEN c.populacao ELSE 0 END) AS populacao_0_4_anos,
    SUM(CASE WHEN c.grupo_idade = '5-9 anos' THEN c.populacao ELSE 0 END) AS populacao_5_9_anos,
    SUM(CASE WHEN c.grupo_idade = '10-14 anos' THEN c.populacao ELSE 0 END) AS populacao_10_14_anos
  FROM `basedosdados.br_ms_populacao.municipio` c
  WHERE ano = 2021
  GROUP BY 1
), 
 
tabela_uf as (
  SELECT 
    tabela_cnes.sigla_uf,    
    tabela_cnes.consultorio_pediatrico,
    tabela_populacao.populacao_0_4_anos,
    tabela_populacao.populacao_5_9_anos,
    tabela_populacao.populacao_10_14_anos,
    populacao_0_4_anos + populacao_5_9_anos + populacao_10_14_anos as pop_criancas_total
  FROM tabela_cnes 
  INNER JOIN tabela_populacao ON tabela_cnes.id_municipio = tabela_populacao.id_municipio
  WHERE tabela_cnes.sigla_uf IN ('AM','AC', 'MT', 'AP', 'PA', 'RO', 'RR', 'TO', 'MA')
)

SELECT 
  t.sigla_uf,
  SUM(t.consultorio_pediatrico) as consultorio_pediatrico,
  SUM(t.pop_criancas_total) as total_populacao_criancas,
  geometria
FROM tabela_uf t
JOIN `basedosdados.br_geobr_mapas.uf` u ON t.sigla_uf = u.sigla_uf
GROUP BY t.sigla_uf, geometria
'''

uf = bd.read_sql(query, billing_project_id='teste-projeto-bd')

#Fix geometrias municipio
df['geometria'] = df['geometria'].apply(lambda s: shapely.wkt.loads(s))
gdf = gpd.GeoDataFrame(df, geometry='geometria', crs='EPSG:4326') # Atribuição do EPSG (Datum)

#Fix geometrias uf
uf['geometria'] = uf['geometria'].apply(lambda s: shapely.wkt.loads(s))
gdf = gpd.GeoDataFrame(uf, geometry='geometria', crs='EPSG:4326') # Atribuição do EPSG (Datum)

df.head() #municipios

uf.head() #UF

# Salvar em .csv para rodar no QGIS
df.to_csv('municipio.csv', sep=',', index=False, header=True) 
uf.to_csv('uf.csv', sep=',', index=False, header=True)

# Depois desse processo, o .csv de cada arquivo, foi levado para o QGIS e realizada a visualização.