# -*- coding: utf-8 -*-
"""rais.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/17kD6YBzKF0ixDUwtBvSVsuc5n9-jwZTw
"""

!pip install basedosdados -q

import basedosdados as bd
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np

query ='''
SELECT A.ano as ano, rem_media_nbrancos, rem_media_brancos, 
(rem_media_nbrancos/rem_media_brancos) AS wage_gap
FROM
    (SELECT ano, AVG(valor_remuneracao_media) as rem_media_nbrancos
    FROM `basedosdados.br_me_rais.microdados_vinculos`
    WHERE raca_cor='4' OR raca_cor='8' OR raca_cor='1'
    AND ano>=2006
    GROUP BY ano) AS A
    LEFT JOIN
    (SELECT ano, AVG(valor_remuneracao_media) as rem_media_brancos
    FROM `basedosdados.br_me_rais.microdados_vinculos`
    WHERE raca_cor='2'
    AND ano>=2006
    GROUP BY ano) AS B
    ON A.ano=B.ano
ORDER by ano
'''

df = bd.read_sql(query, billing_project_id='seu-billing-id')

# criar o gráfico
df.plot(df='ano', y=['rem_media_nbrancos', 'rem_media_brancos'], kind='bar')
# Adicionar título e rótulos dos eixos
plt.title('Renda média de brancos e não brancos ao longo do tempo')
plt.xlabel('Ano')
plt.ylabel('Renda média')
plt.legend(['Não Brancos', 'Brancos'])

# Mostrar o gráfico
plt.show()

plt.savefig("rais.svg", transparent=True, format='svg')